### ISSUE TITLE
Plugins naming convention

### ISSUE THREAD

**Issue by alvarolorentedev** [EvolveLabs/electron-plugins#2]
hello i am finding strange that I am forced to name my plugins at least following the example:

```
<name of the app>-<name of the plugin>
```

if is not like that i get the next crash:
![image](https://cloud.githubusercontent.com/assets/3071208/13211164/4d10c8ce-d936-11e5-9992-c64198698a51.png)
am i doing something worng? is there a gracefulier way to treat the failure of plugin loading?

**Comment by justinmchase** [comment]
I'm not sure I understand. I don't think there is any enforced naming convention on the plugin. What is the name of your plugin so I can investigate it some?

**Comment by alvarolorentedev** [comment]
i am using your [projects default plugin](https://github.com/EvolveLabs/electron-updater-sample-plugin). as per i didnt saw anything relating to the app it depends on in neither the code or the package.json, am i missing something? 
I have push and tagged the failing code if you want to [have a look](https://github.com/Hatisoft/koteky/releases/tag/0.0.1).

**Comment by alvarolorentedev** [comment]
ok i was looking at why this happens and its when the main package is not publish in npm (even if the plugin is publish). I will look more into it...but it might be bot a problem in electron-plugins but more in electron updater. Anyway it has a work around that is publish the main package.
